-- public.cuenta definition

-- Drop table

-- DROP TABLE public.cuenta;

CREATE TABLE public.cuenta (
	id serial4 NOT NULL,
	activo bool NOT NULL,
	apellido varchar(255) NULL,
	eliminado bool NOT NULL,
	keycloak_id varchar(255) NULL,
	mail varchar(255) NULL,
	nombre varchar(255) NULL,
	razon_social varchar(255) NULL,
	ultima_notificacion date NULL,
	url_logo varchar(255) NULL,
	CONSTRAINT cuenta_pkey PRIMARY KEY (id),
	CONSTRAINT uk_ml7ep3uukstgha3g2yuygy5f UNIQUE (keycloak_id)
);


-- public.descarga_fuente_anmat definition

-- Drop table

-- DROP TABLE public.descarga_fuente_anmat;

CREATE TABLE public.descarga_fuente_anmat (
	id int4 NOT NULL,
	fecha_ultima_descarga date NULL,
	CONSTRAINT descarga_fuente_anmat_pkey PRIMARY KEY (id)
);


-- public.disposicion definition

-- Drop table

-- DROP TABLE public.disposicion;

CREATE TABLE public.disposicion (
	id serial4 NOT NULL,
	descripcion varchar(255) NULL,
	disposicion_id varchar(255) NOT NULL,
	eliminado bool NOT NULL,
	fecha_de_aparicion timestamp NOT NULL,
	fecha_de_publicacion timestamp NOT NULL,
	fechayhora_revision timestamp NULL,
	nombre_pdf varchar(255) NULL,
	revisado bool NOT NULL,
	url varchar(255) NOT NULL,
	archivo varchar(255) NULL,
	CONSTRAINT disposicion_pkey PRIMARY KEY (id)
);


-- public.frontend_routes definition

-- Drop table

-- DROP TABLE public.frontend_routes;

CREATE TABLE public.frontend_routes (
	id serial4 NOT NULL,
	alternative_path varchar(255) NULL,
	description text NULL,
	eliminado bool NOT NULL,
	fecha_alta date NULL,
	fecha_ultima_modificacion date NULL,
	"name" varchar(255) NULL,
	"path" varchar(255) NULL,
	usuario_alta varchar(255) NULL,
	usuario_ultima_modificacion varchar(255) NULL,
	CONSTRAINT frontend_routes_pkey PRIMARY KEY (id)
);


-- public.busqueda definition

-- Drop table

-- DROP TABLE public.busqueda;

CREATE TABLE public.busqueda (
	id serial4 NOT NULL,
	activo bool NOT NULL,
	destinatarios varchar(255) NULL,
	eliminado bool NOT NULL,
	fechayhora_generacion_busqueda timestamp NULL,
	fuente_de_informacion int4 NOT NULL,
	nombre_busqueda varchar(255) NULL,
	palabras_de_busqueda varchar(255) NULL,
	cuenta_id int4 NULL,
	CONSTRAINT busqueda_pkey PRIMARY KEY (id),
	CONSTRAINT ukfum68md9n5iwk3qtsnu15mx20 UNIQUE (cuenta_id, nombre_busqueda),
	CONSTRAINT fko85bu0wplnwd4f2t29okp3mna FOREIGN KEY (cuenta_id) REFERENCES public.cuenta(id)
);


-- public.busqueda_historica definition

-- Drop table

-- DROP TABLE public.busqueda_historica;

CREATE TABLE public.busqueda_historica (
	id serial4 NOT NULL,
	desde bytea NULL,
	destinatarios varchar(255) NULL,
	eliminado bool NOT NULL,
	enviada bool NOT NULL,
	fechayhora_creacion date NULL,
	fuente_de_informacion int4 NOT NULL,
	hasta bytea NULL,
	palabras_de_busqueda varchar(255) NULL,
	cuenta_id int4 NULL,
	CONSTRAINT busqueda_historica_pkey PRIMARY KEY (id),
	CONSTRAINT fkbn3c12gw3m2lyir8vj15ceeiu FOREIGN KEY (cuenta_id) REFERENCES public.cuenta(id)
);


-- public.disposicion_contenido definition

-- Drop table

-- DROP TABLE public.disposicion_contenido;

CREATE TABLE public.disposicion_contenido (
	id bigserial NOT NULL,
	contenido text NULL,
	disposicion_id int4 NULL,
	embedding_vector public.vector NULL,
	CONSTRAINT disposicion_contenido_pkey PRIMARY KEY (id),
	CONSTRAINT fk_disposicion_contenido_disposicion FOREIGN KEY (disposicion_id) REFERENCES public.disposicion(id)
);


-- public.email definition

-- Drop table

-- DROP TABLE public.email;

CREATE TABLE public.email (
	id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	body text NULL,
	enviado bool NOT NULL,
	subject varchar(255) NULL,
	to_email varchar(255) NULL,
	fecha_creacion timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL,
	fecha_enviado timestamp(6) NULL,
	cuenta_id int4 NULL,
	CONSTRAINT email_pkey PRIMARY KEY (id),
	CONSTRAINT fk_email_cuenta FOREIGN KEY (cuenta_id) REFERENCES public.cuenta(id)
);


-- public."overlay" definition

-- Drop table

-- DROP TABLE public."overlay";

CREATE TABLE public."overlay" (
	id serial4 NOT NULL,
	completed bool NOT NULL,
	eliminado bool NOT NULL,
	cuenta_id int4 NULL,
	CONSTRAINT overlay_pkey PRIMARY KEY (id),
	CONSTRAINT fkluy17w2ga0fjc55my5dfmw0c6 FOREIGN KEY (cuenta_id) REFERENCES public.cuenta(id)
);


-- public.alerta_generada definition

-- Drop table

-- DROP TABLE public.alerta_generada;

CREATE TABLE public.alerta_generada (
	id serial4 NOT NULL,
	eliminado bool NOT NULL,
	enviada bool NOT NULL,
	estado_alerta int4 NULL,
	fechayhora_ocurrencia timestamp NULL,
	leido bool NOT NULL,
	busqueda_id int4 NOT NULL,
	disposicion_id int4 NULL,
	CONSTRAINT alerta_generada_pkey PRIMARY KEY (id),
	CONSTRAINT fk6r4luvqhhiwod8ttxt1idpgjk FOREIGN KEY (disposicion_id) REFERENCES public.disposicion(id),
	CONSTRAINT fkrgjqbcam8dm6da6xnkx3et92h FOREIGN KEY (busqueda_id) REFERENCES public.busqueda(id)
);


-- public.alerta_generada_historica definition

-- Drop table

-- DROP TABLE public.alerta_generada_historica;

CREATE TABLE public.alerta_generada_historica (
	id serial4 NOT NULL,
	eliminado bool NOT NULL,
	enviada bool NOT NULL,
	estado_alerta int4 NULL,
	fechayhora_ocurrencia timestamp NULL,
	leido bool NOT NULL,
	busqueda_historica_id int4 NOT NULL,
	disposicion_id int4 NULL,
	CONSTRAINT alerta_generada_historica_pkey PRIMARY KEY (id),
	CONSTRAINT fk54tu7sp78iqyf1d3hg7dod4nb FOREIGN KEY (busqueda_historica_id) REFERENCES public.busqueda_historica(id),
	CONSTRAINT fkjk46ao6qwq8xedb7f0gy18dk5 FOREIGN KEY (disposicion_id) REFERENCES public.disposicion(id)
);